utcdatetime: add proper sanity checks for UTCDateTime(..., julday=..)
right now passing invalid juldays can result in misleading error messages, because
julday is silently discarded when encountering out-of-bounds values that
internally in datetime.datetime.strptime(..., '%Y%j') raise "ValueError:
unconverted data remains:"

In [1]: UTCDateTime(year=2017, julday=367)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0e1465633d82> in <module>()
----> 1 UTCDateTime(year=2017, julday=367)

/home/megies/git/obspy-master/obspy/core/utcdatetime.py in __init__(self, *args, **kwargs)
    357             kwargs['microsecond'] = int(round(_frac * 1e6))
    358             args = args[0:5]
--> 359         dt = datetime.datetime(*args, **kwargs)
    360         self._from_datetime(dt)
    361

TypeError: Required argument 'month' (pos 2) not found

This changes this to:

In [1]: UTCDateTime(year=2017, julday=367)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-0e1465633d82> in <module>()
----> 1 UTCDateTime(year=2017, julday=367)

/home/megies/git/obspy-master/obspy/core/utcdatetime.py in __init__(self, *args, **kwargs)
    342             if not (0 <= int(kwargs['julday']) <= 366):
    343                 msg = "'julday' out of bounds: {!s}".format(kwargs['julday'])
--> 344                 raise ValueError(msg)
    345             if 'year' in kwargs:
    346                 # year given as kwargs

ValueError: 'julday' out of bounds: 367