core:
 - changing the silly way the options were handled in my first shot at convenience methods filter/trigger on stream/trace (passing on a dict instead of simply using **kwargs)
 - being nice. old code works, throws DeprecationWarning (using a decorator)
 - also adapting API pages
 - removing some print statements when passing unexpected kwargs or omitting necessary kwargs to convenience methods. no need to be overly verbose, TypeError message displayed by Python is good enough ("fct() got unexpected keyword argument")
 - changing a few Error types
 - adapting some tests for convenience methods (some were not working as expected beforehand anyway.. :/)